test_hex = {(0, 0): ['mountain', 'jaguar', None], (1, 0): ['forest', None, None], (2, 0): ['forest', None, None],
            (3, 0): ['swamp', None, None], (4 ,0): ['swamp', None, None], (5, 0): ['mountain', None, None],
            (6, 0): ['mountain', None, None], (0, 1): ['swamp', 'jaguar', None], (0, 2): ['forest', None, None],
            (0, 3): ['forest', None, None], (0, 4): ['forest', None, None], (0, 5): ['water', None, None],
            (0, -1): ['forest', None, None], (1, -1): ['water', None, None], (2, -1): ['swamp', None, None],
            (3, -1): ['swamp', None, None], (4, -1): ['desert', None, None], (5, -1): ['desert', 'bear', None],
            (1, -2): ['water', None, None], (2, -2): ['water', None, None], (3, -2): ['mountain', None, None],
            (4, -2): ['mountain', 'bear', None], (2, -3): ['water', None, 'blue monument'], (3, -3): ['mountain', None, None],
            (-1, 0): ['mountain', None, None], (-1, 1): ['mountain', None, None], (-1, 2): ['mountain', None, None],
            (-1, 3): ['water', None, None], (-1, 4): ['water', None, None], (-2, 1): ['mountain', None, None],
            (-2, 2): ['water', None, 'white hut'], (-2, 3): ['water', None, None], (-3, 2): ['water', None, None],
            (1, 1): ['swamp', 'jaguar', None], (2, 1): ['forest', None, None], (3, 1): ['swamp', None, None],
            (4, 1): ['mountain', None, None], (5, 1): ['mountain', None, None], (6, 1): ['water', None, None],
            (7, 1): ['water', 'jaguar', None], (1, 2): ['swamp', None, None], (1, 3): ['forest', None, None],
            (1, 4): ['water', None, None], (1, 5): ['water', None, None], (1, 6): ['swamp', None, None],
            (2, 2): ['swamp', None, 'green monument'], (3, 2): ['desert', None, None], (4, 2): ['desert', None, None],
            (5, 2): ['mountain', None, None], (6, 2): ['water', None, None], (7, 2): ['forest', None, None],
            (8, 2): ['forest', 'jaguar', None], (2, 3): ['forest', None, None], (2, 4): ['water', None, None],
            (2, 5): ['water', None, None], (2, 6): ['swamp', None, None], (2, 7): ['swamp', None, None],
            (3, 3): ['forest', None, None], (4, 3): ['desert', None, None], (5, 3): ['desert', None, None],
            (6, 3): ['desert', None, None], (7, 3): ['forest', None, None], (8, 3): ['mountain', None, None],
            (9, 3): ['swamp', None, None], (3, 4): ['forest', None, None], (3, 5): ['desert', None, None],
            (3, 6): ['desert', None, None], (3, 7): ['swamp', None, None], (3, 8): ['water', 'bear', None],
            (4, 4): ['forest', None, None], (5, 4): ['desert', None, None], (6, 4): ['desert', None, 'green hut'],
            (7, 4): ['mountain', None, None], (8, 4): ['mountain', None, 'white monument'],
            (9, 4): ['swamp', None, None], (10, 4): ['swamp', None, None], (4, 5): ['desert', 'bear', 'blue hut'],
            (4, 6): ['desert', 'bear', None], (4, 7): ['water', None, None], (4, 8): ['water', 'bear', None],
            (4, 9): ['mountain', 'bear', None], (5, 5): ['forest', 'bear', None], (6, 5): ['desert', None, None],
            (7, 5): ['mountain', None, None], (8, 5): ['desert', None, None], (9, 5): ['forest', None, None],
            (10, 5): ['forest', 'jaguar', None], (11, 5): ['swamp', 'jaguar', None], (5, 6): ['desert', None, None],
            (5, 7): ['water', None, None], (5, 8): ['water', None, None], (5, 9): ['mountain', None, None],
            (5, 10): ['mountain', None, None], (6, 6): ['desert', None, None], (7, 6): ['desert', None, None],
            (8, 6): ['desert', None, None], (9, 6): ['forest', None, None], (10, 6): ['forest', 'jaguar', None],
            (6, 7): ['desert', None, None], (6, 8): ['desert', None, None], (6, 9): ['mountain', None, None],
            (6, 10): ['mountain', None, None], (7, 7): ['swamp', None, None], (8, 7): ['forest', None, None],
            (9, 7): ['forest', None, None], (7, 8): ['swamp', None, None], (7, 9): ['swamp', None, None],
            (8, 8): ['swamp', None, None]}

test_hints = ((3, ('building', 'white')), (0, ('swamp', 'desert')), (1, ('water')))
'''пример для животных: (2, ('animal', 'bear'))
   пример для типа строения: (3, ('building', 'monument'))'''
